### ISSUE TITLE
Exception on registration screen: "Build scheduled during frame."

### ISSUE THREAD

**Issue by JohnSiegel** [PhitNest/phitnest#118] opened 2023-12-13 14:56 UTC
When the keyboard is visible on the registration screen and you scroll to dismiss it, an exception is thrown. Must be ran with console output to see error message.

**Comment by CaglarKullu** [comment] 2024-01-18 16:57
Hi ! Could you please add an SS and which emulator did you use? I couldn't manage to replicating it @JohnSiegel

**Comment by CaglarKullu** [comment] 2024-01-28 16:26
Couldn't reproduce so I am closing

**Closed by CaglarKullu** 2024-01-28 16:26 UTC
Labels: bug
